# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: "client1,postgres:client2,postgres"
    build:
      context: .
      dockerfile: ./Dockerfile
  # volumes:
  #  ../src/main/resources/db/0-init.sql:/docker-entrypoint-initdb.d/0-init.sql
  #  ./DDL.sql: /docker-entrypoint-initdb.d/DDL.sql
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080